[package]
name = "rust-simple-chat"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "chat"
path = "src/bin/chat/main.rs"

[[bin]]
name = "worker"
path = "src/bin/worker/main.rs"

[dependencies]
axum = { version = "0.8.1", features = ["http1", "http2", "json", "macros"] }
axum-extra = { version = "0.10.0", features = ["typed-header"] }
tokio = { version = "1.43.0", features = ["full"] }
anyhow = { version = "1.0.95", default-features = false }
serde = { version = "1.0.217", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.28", features = ["derive", "env"] }
humantime = { version = "2.1.0" }
deadpool-postgres = { version = "0.14.1" }
tokio-postgres = { version = "0.7.13", features = ["with-chrono-0_4"] }
tokio-postgres-utils = { version = "0.2.0" }
tower = { version = "0.5.2" }
tower-http = { version = "0.6.2", features = ["cors"] }
validator = { version = "0.20.0", features = ["derive"] }
thiserror = { version = "2.0.11" }
jsonwebtoken = { version = "9.3.1" }
metrics-exporter-prometheus = { version = "0.16.2", default-features = false }
metrics = { version = "0.24.1", default-features = false }
tracing-subscriber = {version = "0.3.19", features = ["env-filter", "json"] }
tracing = {version = "0.1.41"}
