[package]
name = "rust-simple-chat"
version = "0.1.0"
edition = "2024"

[profile.production]
inherits = "release"
lto = true

[profile.profiling]
inherits = "release"
debug = true

[[bin]]
name = "chat"
path = "src/bin/chat/main.rs"

[[bin]]
name = "worker"
path = "src/bin/worker/main.rs"

[[bench]]
name = "benches"
harness = false

[dependencies]
anyhow = { version = "1.0.97", default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
chrono = { version = "0.4.40", features = ["serde"] }
clap = { version = "4.5.32", features = ["derive", "env"] }
humantime = { version = "2.2.0" }
validator = { version = "0.20.0", features = ["derive"] }
thiserror = { version = "2.0.12" }
async-trait = { version = "0.1.88" }
mime = { version = "0.3.17" }
serde_json = { version = "1.0.140" }
mockall = { version = "0.13.1" }
jsonwebtoken = { version = "9.3.1" }

axum = { version = "0.8.1", features = ["http1", "http2", "json", "macros"] }
axum-core = { version = "0.5.0" }
axum-extra = { version = "0.10.0", features = ["typed-header"] }
tower = { version = "0.5.2", features = ["timeout"] }
tower-http = { version = "0.6.2", features = [
    "cors",
    "catch-panic",
    "timeout",
    "compression-gzip",
    "sensitive-headers",
    "propagate-header",
    "trace"
] }
http = { version = "1.3.1" }
http-body-util = "0.1.3"
utoipa = { version = "5.3.1", features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum", "reqwest"] }
utoipa-axum = { version = "0.2.0" }
utoipa-redoc = { version = "6.0.0", features = ["axum"] }
utoipa-rapidoc = { version = "6.0.0", features = ["axum"] }
utoipa-scalar = { version = "0.3.0", features = ["axum"] }

tokio = { version = "1.44.1", features = ["full"] }
tokio-util = "0.7.14"
tokio-postgres = { version = "0.7.13", features = ["with-chrono-0_4"] }
tokio-postgres-utils = { version = "0.2.0" }
deadpool-postgres = { version = "0.14.1" }

metrics = { version = "0.24.1", default-features = false }
metrics-exporter-prometheus = { version = "0.16.2", default-features = false }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
tracing-opentelemetry = { version = "0.29.0" }
opentelemetry = { version = "0.28.0", features = ["trace", "internal-logs"] }
opentelemetry-otlp = { version = "0.28.0", features = ["trace", "http-proto"] }
opentelemetry_sdk = { version = "0.28.0", features = ["rt-tokio"] }
