version: '3.9'
services:
  postgres:
    image: postgres:14.2-alpine
    container_name: simple-chat-postgres
    env_file:
      - .env.template
    ports:
      - "54320:5432"
    volumes:
      - ./scripts/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh
      - simple-chat-pgdata:/var/lib/postgresql/data
    networks:
      - simple-chat-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  simple-chat-network:
    driver: bridge

volumes:
  simple-chat-pgdata: