name: build and test

on:
  workflow_run:
    workflows: [ "build" ]
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          cargo build --verbose

  test:
    needs: [ "build" ]
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          cargo test --verbose

  coverage:
    needs: [ "build" ]
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120