name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Export variables from secret
        run: |
          ENV_JSON='${{ secrets.APPSETTINGS_VARIABLES_FOR_TESTS }}'
          echo "$ENV_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo $JWT_SECRET
          cargo test --verbose