name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #      - name: Export variables from secret
      #        run: |
      #          ENV_JSON='${{ secrets.SETTINGS }}'
      #          echo "$ENV_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          echo $JWT_SECRET
          cargo test --verbose